version: '3'
services:
  mysql:
      image: mysql:latest
      restart: always
      # command: --init-file /init.sql
      # volumes:
      #     - ./init.sql:/init.sql
      environment:
        MYSQL_DATABASE: 'flycsv'
        MYSQL_USER: 'root123'
        MYSQL_PASSWORD: 'root123'
        MYSQL_ROOT_PASSWORD: 'root'
      ports:
        - '3307:3306'
  
  backend:
    build: ./flycsvBackend
    ports:
      - "8000:8000"
    volumes:
      - ./flycsvBackend:/app
    links:
      - mysql:mysql1
    depends_on:
      - mysql

  frontend:
    build: ./flycsv-app
    ports:
      - "4200:80"
    volumes:
      - ./flycsv-app:/app
    depends_on:
      - backend
