version: '3.8'

services:
  frontend:
    build: ./flycsv-app
    ports:
      - "4200:80"

  backend:
    build: ./flycsvBackend
    ports:
      - "8000:8000"

  mysql:
    container_name: symfony_mysql
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    command: --init-file /init.sql
    volumes:
      - ./init.sql:/init.sql
      - db_data:/var/lib/mysql
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: 'flycsv'
      MYSQL_USER: 'root123'
      MYSQL_PASSWORD: 'root123'
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  db_data: